env:
  es6: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project:
    - ./tsconfig.json
    - ./**/tsconfig.json
    - ./**/tsconfig.eslint.json
extends:
  - '@alex-taxiera/eslint-config-ts'
rules: {}
