extends: standard
rules:
  arrow-parens:
    - error
  no-lonely-if:
    - error
  curly:
    - error
    - all
  array-bracket-spacing:
    - error
    - always
  no-multi-spaces:
    - error
    -
      ignoreEOLComments: true
  max-len:
    - error
    -
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreUrls: true